package git

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/Kaiman42/reposync/internal/ui"
)

func GetGitStatus(repoPath string) string {
	if _, err := os.Stat(filepath.Join(repoPath, ".git")); os.IsNotExist(err) {
		return "not_init"
	}

	cmd := exec.Command("git", "status", "--porcelain")
	cmd.Dir = repoPath
	cmd.SysProcAttr = ui.GetSysProcAttr()
	output, _ := cmd.Output()

	lines := strings.Split(strings.TrimSpace(string(output)), "\n")
	hasUntracked := false
	hasModified := false

	for _, line := range lines {
		if line == "" {
			continue
		}

		if strings.Contains(line, "desktop.ini") || strings.Contains(line, ".directory") {
			continue
		}

		statusPart := line[:2]
		if statusPart == "??" {
			hasUntracked = true
		} else {
			hasModified = true
		}
	}

	if hasUntracked {
		return "untracked"
	}
	if hasModified {
		return "commit"
	}

	return GetSyncStatus(repoPath)
}

func GetSyncStatus(path string) string {
	cmd := exec.Command("git", "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}")
	cmd.Dir = path
	cmd.SysProcAttr = ui.GetSysProcAttr()
	err := cmd.Run()
	if err != nil {
		remoteCmd := exec.Command("git", "remote")
		remoteCmd.Dir = path
		remoteCmd.SysProcAttr = ui.GetSysProcAttr()
		remoteOut, _ := remoteCmd.Output()
		if strings.TrimSpace(string(remoteOut)) == "" {
			return "no_remote"
		}
		return "pending_sync"
	}

	aheadCmd := exec.Command("git", "rev-list", "@{u}..HEAD", "--count")
	aheadCmd.Dir = path
	aheadCmd.SysProcAttr = ui.GetSysProcAttr()
	aheadOut, _ := aheadCmd.Output()
	ahead := strings.TrimSpace(string(aheadOut))

	behindCmd := exec.Command("git", "rev-list", "HEAD..@{u}", "--count")
	behindCmd.Dir = path
	behindCmd.SysProcAttr = ui.GetSysProcAttr()
	behindOut, _ := behindCmd.Output()
	behind := strings.TrimSpace(string(behindOut))

	if ahead != "0" || behind != "0" {
		return "pending_sync"
	}

	return "synced"
}

func FindRepos(bases []string) []string {
	var repos []string
	seen := make(map[string]bool)
	for _, base := range bases {
		files, err := os.ReadDir(base)
		if err != nil {
			continue
		}
		for _, f := range files {
			if f.IsDir() {
				path := filepath.Join(base, f.Name())
				if !seen[path] {
					repos = append(repos, path)
					seen[path] = true
				}
			}
		}
	}
	return repos
}

func GetRemoteURL(path string) string {
	cmd := exec.Command("git", "remote", "get-url", "origin")
	cmd.Dir = path
	cmd.SysProcAttr = ui.GetSysProcAttr()
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	url := strings.TrimSpace(string(out))
	if strings.HasPrefix(url, "git@") {
		url = strings.Replace(url, ":", "/", 1)
		url = strings.Replace(url, "git@", "https://", 1)
		url = strings.TrimSuffix(url, ".git")
	}
	return url
}

func GetRepoLastMod(path string) time.Time {
	cmd := exec.Command("git", "log", "-1", "--format=%ct")
	cmd.Dir = path
	cmd.SysProcAttr = ui.GetSysProcAttr()
	out, err := cmd.Output()
	if err == nil {
		var sec int64
		fmt.Sscanf(strings.TrimSpace(string(out)), "%d", &sec)
		return time.Unix(sec, 0)
	}
	info, _ := os.Stat(path)
	if info != nil {
		return info.ModTime()
	}
	return time.Now()
}

func InstallHooksAll(bases []string) {
	repos := FindRepos(bases)
	self, _ := os.Executable()
	for _, repo := range repos {
		InstallHook(repo, self)
	}
	fmt.Printf("Hooks installed in %d repositories.\n", len(repos))
}

func InstallHook(repoPath, selfPath string) {
	hooksDir := filepath.Join(repoPath, ".git", "hooks")
	os.MkdirAll(hooksDir, 0755)

	hookNames := []string{"post-commit", "post-merge", "post-checkout", "post-rewrite", "post-applypatch", "post-reset", "post-update", "post-switch"}

	selfPath = strings.ReplaceAll(selfPath, "\\", "/")

	content := fmt.Sprintf("#!/bin/bash\n# Auto-generated by RepoSync\n\"%s\" run -q >/dev/null 2>&1 &\nexit 0\n", selfPath)

	for _, name := range hookNames {
		hookPath := filepath.Join(hooksDir, name)
		os.WriteFile(hookPath, []byte(content), 0755)
	}
}
