// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPath(arg1:string):Promise<void>;

export function GetConfig():Promise<Array<string>>;

export function GetRepoDetails(arg1:string):Promise<Record<string, any>>;

export function GetRepos():Promise<Array<main.RepoInfo>>;

export function Minimize():Promise<void>;

export function OpenAction(arg1:string,arg2:string):Promise<void>;

export function Quit():Promise<void>;

export function RemovePath(arg1:string):Promise<void>;
