// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPath(arg1) {
  return window['go']['main']['App']['AddPath'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRepoDetails(arg1) {
  return window['go']['main']['App']['GetRepoDetails'](arg1);
}

export function GetRepos() {
  return window['go']['main']['App']['GetRepos']();
}

export function OpenAction(arg1, arg2) {
  return window['go']['main']['App']['OpenAction'](arg1, arg2);
}

export function RemovePath(arg1) {
  return window['go']['main']['App']['RemovePath'](arg1);
}
